#define irsend_var irsend

//epson_pr1 - eb-2255u     (address 0x5583)

#define epson_pr1_esc           irsend_var.sendNEC(0xC1AA21DE, 32);  //esc               (command 0x84)
#define epson_pr1_enter         irsend_var.sendNEC(0xC1AAA15E, 32);  //enter             (command 0x85)
#define epson_pr1_page_up       irsend_var.sendNEC(0xC1AA619E, 32);  //pageup            (command 0x86)
#define epson_pr1_page_down     irsend_var.sendNEC(0xC1AAE11E, 32);  //pagedown          (command 0x87)
#define epson_pr1_zoom_in       irsend_var.sendNEC(0xC1AA11EE, 32);  //zoom+             (command 0x88)
#define epson_pr1_zoom_out      irsend_var.sendNEC(0xC1AA916E, 32);  //zoom-             (command 0x89)
#define epson_pr1_power         irsend_var.sendNEC(0xC1AA09F6, 32);  //power             (command 0x90)
#define epson_pr1_power_on      irsend_var.sendNEC(0xC1AAFE01, 32);  //power on          (command 0x7F)
#define epson_pr1_power_off     irsend_var.sendNEC(0xC1AA8976, 32);  //power off         (command 0x91)
#define epson_pr1_up            irsend_var.sendNEC(0xC1AA0DF2, 32);  //up                (command 0xB0)
#define epson_pr1_down          irsend_var.sendNEC(0xC1AA4DB2, 32);  //down              (command 0xB2)
#define epson_pr1_left          irsend_var.sendNEC(0xC1AACD32, 32);  //left              (command 0xB3)
#define epson_pr1_right         irsend_var.sendNEC(0xC1AA8D72, 32);  //right             (command 0xB1)
#define epson_pr1_1             irsend_var.sendNEC(0xC1AA857A, 32);  //1                 (command 0xA1)
#define epson_pr1_2             irsend_var.sendNEC(0xC1AA45BA, 32);  //2                 (command 0xA2)
#define epson_pr1_3             irsend_var.sendNEC(0xC1AAC53A, 32);  //3                 (command 0xA3)
#define epson_pr1_4             irsend_var.sendNEC(0xC1AA25DA, 32);  //4                 (command 0xA4)
#define epson_pr1_5             irsend_var.sendNEC(0xC1AAA55A, 32);  //5                 (command 0xA5)
#define epson_pr1_6             irsend_var.sendNEC(0xC1AA659A, 32);  //6                 (command 0xA6)
#define epson_pr1_7             irsend_var.sendNEC(0xC1AAE51A, 32);  //7                 (command 0xA7)
#define epson_pr1_8             irsend_var.sendNEC(0xC1AA15EA, 32);  //8                 (command 0xA8)
#define epson_pr1_9             irsend_var.sendNEC(0xC1AA956A, 32);  //9                 (command 0xA9)
#define epson_pr1_0             irsend_var.sendNEC(0xC1AA05FA, 32);  //0                 (command 0xA0)
#define epson_pr1_vol_down      irsend_var.sendNEC(0xC1AA9966, 32);  //vol-              (command 0x99)
#define epson_pr1_vol_up        irsend_var.sendNEC(0xC1AA19E6, 32);  //vol+              (command 0x98)
#define epson_pr1_menu          irsend_var.sendNEC(0xC1AA59A6, 32);  //menu              (command 0x9A)
#define epson_pr1_search        irsend_var.sendNEC(0xC1AA31CE, 32);  //source search     (command 0x8c)
#define epson_pr1_computer      irsend_var.sendNEC(0xC1AA29D6, 32);  //source computer   (command 0x94)
#define epson_pr1_hdmi_video    irsend_var.sendNEC(0xC1AA0EF1, 32);  //source hdmi/video (command 0x70)
#define epson_pr1_usb           irsend_var.sendNEC(0xC1AA6E91, 32);  //source usb        (command 0x76)
#define epson_pr1_lan           irsend_var.sendNEC(0xC1AA2ED1, 32);  //source lan        (command 0x74)
#define epson_pr1_hdmi1         irsend_var.sendNEC(0xC1AA738C, 32);  //source hdmi1      (command 0xCE)
#define epson_pr1_hdmi2         irsend_var.sendNEC(0xC1AAF30C, 32);  //source hdmi2      (command 0xCF)
#define epson_pr1_usb_display   irsend_var.sendNEC(0xC1AA0BF4, 32);  //source usb display(command 0xD0)
#define epson_pr1_usb           irsend_var.sendNEC(0xC1AA8B74, 32);  //source usb        (command 0xD1)
#define epson_pr1_usb_display   irsend_var.sendNEC(0xC1AACB34, 32);  //source lan        (command 0xD3)
#define epson_pr1_scr_mirroring irsend_var.sendNEC(0xC1AABB44, 32);  //source screen mirr(command 0xDD)
#define epson_pr1_home          irsend_var.sendNEC(0xC1AAA956, 32);  //home              (command 0x95)
#define epson_pr1_mute          irsend_var.sendNEC(0xC1AAC936, 32);  //mute              (command 0x93)
#define epson_pr1_split         irsend_var.sendNEC(0xC1AA41BE, 32);  //split             (command 0x82)
#define epson_pr1_freeze        irsend_var.sendNEC(0xC1AA49B6, 32);  //freeze            (command 0x92)
#define epson_pr1_user          irsend_var.sendNEC(0xC1AAF906, 32);  //user              (command 0x9F)
#define epson_pr1_pointer       irsend_var.sendNEC(0xC1AAD926, 32);  //pointer           (command 0x9B)
#define epson_pr1_auto          irsend_var.sendNEC(0xC1AA7986, 32);  //auto              (command 0x9E)
#define epson_pr1_aspect        irsend_var.sendNEC(0xC1AA51AE, 32);  //aspect            (command 0x8A)
#define epson_pr1_color_mode    irsend_var.sendNEC(0xC1AAF10E, 32);  //color mode        (command 0x8F)
#define epson_pr1_link_menu     irsend_var.sendNEC(0xC1AA06F9, 32);  //link menu         (command 0x60)
#define epson_pr1_gesture       irsend_var.sendNEC(0xC1AAB24D, 32);  //gesture           (command 0x4D)
#define epson_pr1_screen_fit    irsend_var.sendNEC(0xC1AAFC03, 32);  //screen fit        (command 0x3F)
